spring:
  application:
    name: book-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}

  flyway:
    url: ${app.datasource.url}
    user: ${app.datasource.username}
    password: ${app.datasource.password}

app:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  minio:
    url: http://localhost:9000
    accessKey: ${MINIO_USER}
    secretKey: ${MINIO_PASSWORD}
  clickhouse:
    url: jdbc:ch://localhost:8123/${CLICKHOUSE_DB}
    user: ${CLICKHOUSE_USER}
    password: ${CLICKHOUSE_PASSWORD}

server:
  port: ${SERVER_PORT}