CREATE TABLE IF NOT EXISTS BOOKS
(
    BOOK_ID       BIGSERIAL PRIMARY KEY,
    TITLE         VARCHAR(255)  NOT NULL,
    GENRE         VARCHAR(255)  NOT NULL,
    CREATION_YEAR SMALLINT      NOT NULL,
    PAGES         SMALLINT      NOT NULL,
    DESCRIPTION   TEXT,
    AMOUNT        DECIMAL(8, 2) NOT NULL DEFAULT 0,
    BINDING       VARCHAR(255)  NOT NULL,
    CREATED_AT    TIMESTAMP     NOT NULL,
    MODIFIED_AT   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID   BIGSERIAL PRIMARY KEY,
    FIRSTNAME   VARCHAR(255) NOT NULL,
    SURNAME     VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS AUTHORS_BOOKS
(
    AUTHOR_ID BIGSERIAL REFERENCES AUTHORS (AUTHOR_ID) NOT NULL,
    BOOK_ID   BIGSERIAL REFERENCES BOOKS (BOOK_ID)     NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLISHERS
(
    PUBLISHER_ID BIGSERIAL PRIMARY KEY,
    NAME         VARCHAR(255) NOT NULL,
    DESCRIPTION  TEXT,
    PHONE        VARCHAR(12),
    ADDRESS      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PUBLISHERS_BOOKS
(
    PUBLISHER_ID BIGSERIAL REFERENCES PUBLISHERS (PUBLISHER_ID) NOT NULL,
    BOOK_ID      BIGSERIAL REFERENCES BOOKS (BOOK_ID)           NOT NULL
);

CREATE TABLE IF NOT EXISTS IMAGES
(
    IMAGE_ID    BIGSERIAL PRIMARY KEY,
    BOOK_ID     BIGINT REFERENCES BOOKS (BOOK_ID) NOT NULL,
    URL         VARCHAR(255)                      NOT NULL UNIQUE,
    CREATED_AT  TIMESTAMP                         NOT NULL,
    MODIFIED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ORDER_ID    BIGSERIAL PRIMARY KEY,
    TOTAL_PRICE DECIMAL(8, 2) NOT NULL DEFAULT 0,
    CREATED_AT  TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS WAREHOUSES
(
    WAREHOUSE_ID BIGSERIAL PRIMARY KEY,
    ADDRESS      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS WAREHOUSES_BOOKS
(
    BOOK_ID      BIGSERIAL REFERENCES BOOKS (BOOK_ID)           NOT NULL,
    WAREHOUSE_ID BIGSERIAL REFERENCES WAREHOUSES (WAREHOUSE_ID) NOT NULL,
    QUANTITY     BIGINT                                         NOT NULL DEFAULT 0,
    CREATED_AT   TIMESTAMP                                      NOT NULL,
    MODIFIED_AT  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BUCKETS
(
    ORDER_ID    BIGINT REFERENCES ORDERS (ORDER_ID) NOT NULL,
    BOOK_ID     BIGINT REFERENCES BOOKS (BOOK_ID)   NOT NULL,
    QUANTITY    BIGINT                              NOT NULL DEFAULT 1,
    CREATED_AT  TIMESTAMP                           NOT NULL,
    MODIFIED_AT TIMESTAMP
);





