name: "CI for project"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/frontend-ci.yml